/*
 * created : Nov 18, 2011
 * by : Latief
 */

/*
 * PanelCellPerson.java
 *
 * Created on Nov 18, 2011, 1:21:50 PM
 */
package com.secondstack.swing.table;

import com.secondstack.swing.panel.JPPanelTransparency;

/**
 *
 * @author Latief
 */
public abstract class PanelCell extends JPPanelTransparency {

    /** Creates new form PanelCellPerson */
    public PanelCell() {
        initComponents();
        setAlphaTransparency(0F);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private boolean selected = false;

    public abstract Object getValue();

    public abstract void setValue(Object value);
    
    public abstract void requestDefaultFocusComponent();

    public void setSelected(boolean selected) {
        this.selected = selected;
        if (selected) {
            setAlphaTransparency(0.5F);
            requestFocusInWindow();
            requestDefaultFocusComponent();
        } else {
            setAlphaTransparency(0F);
        }
    }
    
    public boolean isSelected(){
        return this.selected;
    }
}
