/*
 * created : Aug 19, 2011
 * by : Latief
 */

/*
 * JPHeader.java
 *
 * Created on Aug 19, 2011, 9:31:12 PM
 */
package com.secondstack.swing.header;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Point2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Icon;

/**
 *
 * @author Latief
 */
public class JPHeader extends javax.swing.JPanel {

    /** Creates new form JPHeader */
    public JPHeader() {
        initComponents();
        setOpaque(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIcon = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();

        labelHeader.setText("Header");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelHeader)
                    .addComponent(labelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelIcon;
    // End of variables declaration//GEN-END:variables
    private Icon icon;
    private Color colorDarker = new Color(141, 180, 227);
    private Color colorLighter = new Color(228, 237, 248);

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g.create();


        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        float width = getWidth() - 1;
        float height = getHeight() - 1;

        Point2D.Float p1 = new Point2D.Float(0f, 0); // Gradient line start
        Point2D.Float p2 = new Point2D.Float(0f, height / 4 * 3); // Gradient line end

        RoundRectangle2D.Float rectButton = new RoundRectangle2D.Float(0, 0, width, height, 10, 10);

        //Gradient
        GradientPaint g2 = new GradientPaint(p1, colorLighter, p2, colorDarker, true); //cyclicgradient

        //fill gradient RoundReactangle2D
        g2d.setPaint(g2); // Gradient color fill
        g2d.fill(rectButton); // Fill the rectangle

    }

    public Icon getIcon() {
        return icon;
    }

    public void setIcon(Icon icon) {
        this.icon = icon;
    }
    
    public void setHeader(String header){
        labelHeader.setText(header);
    }
    
    public String getHeader(){
        return labelHeader.getText();
    }
}
