/*
 * created : Aug 19, 2011
 * by : Latief
 */

/*
 * FrameTest.java
 *
 * Created on Aug 19, 2011, 9:19:31 PM
 */
package com.secondstack.swing;

import com.secondstack.swing.table.BeanTableModel;
import com.secondstack.swing.table.ModelPerson;
import com.secondstack.swing.table.ObjectTableCellEditor;
import com.secondstack.swing.table.ObjectTableCellRenderrer;
import com.secondstack.swing.table.PanelCellPerson;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Latief
 */
public class FrameTest extends javax.swing.JFrame {

    /** Creates new form FrameTest */
    public FrameTest() {
        initComponents();
        initTableModel();
        scrollPane.getViewport().setOpaque(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new com.secondstack.swing.panel.JPPanel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setOpaque(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setOpaque(false);
        scrollPane.setViewportView(table);

        button.setText("button");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(button))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        System.out.println(modelPersons);
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrameTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private com.secondstack.swing.panel.JPPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private List<ModelPerson> modelPersons;

    private void initTableModel() {
        modelPersons = new ArrayList<ModelPerson>();
        for (int i = 0; i < 10; i++) {
            Person person = new Person();
            person.setNama(Math.random() + "");
            person.setAlamat(Math.random() + "");
            ModelPerson modelPerson = new ModelPerson();
            modelPerson.setString(Math.random() + "");
            modelPerson.setPerson(person);
            modelPerson.setBool(true);
            modelPersons.add(modelPerson);
        }

        String[] columnNames = {"String","Person","Boolean"};
        boolean[] columnEditable = {true,true,true};

        PanelCellPerson panelCellPerson = new PanelCellPerson();
        ObjectTableCellRenderrer personCellRenderrer;
        ObjectTableCellEditor personCellEditor;
        try {
            personCellRenderrer = new ObjectTableCellRenderrer(panelCellPerson);
            personCellEditor = new ObjectTableCellEditor(panelCellPerson);

            BeanTableModel tableModel = new BeanTableModel(modelPersons, columnNames, columnEditable);
            table.setDefaultRenderer(Person.class, personCellRenderrer);
            table.setDefaultEditor(Person.class, personCellEditor);
            table.setRowHeight(panelCellPerson.getPreferredSize().height);
            table.setModel(tableModel);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrameTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrameTest.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
